// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvpyNTwT0vfImfDPixysphcZmQ65Nmh78',
    appId: '1:203304631165:web:ce6cb8a3fd6c3b71ecea14',
    messagingSenderId: '203304631165',
    projectId: 'milckoapk-480ab',
    authDomain: 'milckoapk-480ab.firebaseapp.com',
    storageBucket: 'milckoapk-480ab.appspot.com',
    measurementId: 'G-VHVWBT5PMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfkhNeJhVqzAgqDvmO4mHyhqpIE5mW3j8',
    appId: '1:203304631165:android:a7f8e7a5a86938bcecea14',
    messagingSenderId: '203304631165',
    projectId: 'milckoapk-480ab',
    storageBucket: 'milckoapk-480ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXv5kDzffXoA8cfm9zNQ2RE13ymsG9EFM',
    appId: '1:203304631165:ios:ec632117afc7fa96ecea14',
    messagingSenderId: '203304631165',
    projectId: 'milckoapk-480ab',
    storageBucket: 'milckoapk-480ab.appspot.com',
    iosBundleId: 'com.example.milckoapk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXv5kDzffXoA8cfm9zNQ2RE13ymsG9EFM',
    appId: '1:203304631165:ios:69091de681ccb49cecea14',
    messagingSenderId: '203304631165',
    projectId: 'milckoapk-480ab',
    storageBucket: 'milckoapk-480ab.appspot.com',
    iosBundleId: 'com.example.milckoapk.RunnerTests',
  );
}
